### ISSUE TITLE
Api Login

### ISSUE THREAD

**Issue by V3nomAnc3r** [jonasschmedtmann/complete-node-bootcamp#10]
Hello @jonasschmedtmann how can i login to website with this api and reactjs?
i can't protect my routes, can you please give me a sample.

**Comment by jonasschmedtmann** [comment]
There is no React in this course, so I have no sample, sorry.

**Comment by aqibijaz** [comment]
Hello, @jonasschmedtmann  when I can add a new tour and also add tour locations but on tour page, location makers show but map doesn't show.
Please, can you tell me about this issue?
![map issue](https://user-images.githubusercontent.com/45151704/70848156-0e761e00-1e8f-11ea-8053-8a685eb88a89.jpg)

**Comment by V3nomAnc3r** [comment]
@jonasschmedtmann Ok Sorry, but
for example i dont have pug template and view routes,
my client is running on port 3001 and server 3000,
How can i send cookie to port 3001 and how can i access to isLoggedIn and isProtected (with axios)

can you explain that for me please

**Comment by jonasschmedtmann** [comment]
Please ask this kind of questions in the official course Q&A on Udemy, you will get help there. I like to keep that as a central place for all questions, so that everyone can see them :)
