### ISSUE TITLE
Deleting current user

### ISSUE THREAD

**Issue by Raizo-Jr** [jonasschmedtmann/complete-node-bootcamp#109]
Active status not changing to false after delete user
**Model** `  Active: {
    type: Boolean,
    default: true,
    select: false,
  },`
**Controller** `exports.deleteMe = catchAsync(async (req, res, next) => {
  const user = await User.findByIdAndUpdate(req.user.id, { active: false });

  res.status(204).json({
    status: "success",
    data: null,
  });
});`
**Route** `router.delete("/deleteMe", authController.protect, userController.deleteMe);`
![Capture](https://user-images.githubusercontent.com/75359517/120499851-050fa700-c3de-11eb-97cf-f8e3856410f2.PNG)

**Comment by nvispute** [comment]
I think this is the issue ```{ active: false }```  it should be ```{ Active: false }```.. as you see in the model and the res your the prop is written with capital A and not small a

**Comment by Raizo-Jr** [comment]
@nvispute Thank you, sir. I didn't notice it. Now it's working fine.
