### ISSUE TITLE
zip file downloaded is currupted

### ISSUE THREAD

**Issue by SahilSinghTomar** [jonasschmedtmann/complete-node-bootcamp#184]
not able to extract zip file downloaded

**Comment by SoumyaSubhrajit** [comment]
@SahilSinghTomar what's causing this issue explain a little bit.

**Comment by MJ-Zadran** [comment]
they write like that  The archive is corrupted.

**Comment by MJ-Zadran** [comment]
Yes, There was a problem but not in node bootcamp zipfile. The problem was
network error. Witch cause this error. And now it's fine.
Have a nice day.
