### ISSUE TITLE
SOME ISSUE IN PRODUCTION SIDE ERROR "NEED HELP" 

### ISSUE THREAD

**Issue by SoumyaSubhrajit** [jonasschmedtmann/complete-node-bootcamp#191]
Let me explain what is the error about, 
So basically the API I want to fetch is this -> `127.0.0.1:8000/api/v1/tours/SomeRandomPage`
 **NOTE:** It is working in when `NODE_ENV = development`, but when `NODE_ENV = production`  it no longer working it in loading process it huge time with no response. 
I gave some screenshots for your reference.

HERE IS MY CODE: 
**FILE: errorController.js** 
 ### This is handleCastErrorDB function
```
 const handleCastErrorDB = err => {
  const message = `Invalid ${err.path}: ${err.value}.`;
  return new AppError(message, 400);
};
```

### This is sending in error in response:--

```
const sendErrorProd = function (err, res) {
  if (err.isOperational) {
    res.status(err.statusCode).json({
      status: err.status,
      message: err.message
    })
  } else {
    console.log('Error: something went wrong!');
    res.satus(500).json({
      status: 'error',
      message: 'Somthing went wrong!'
    })
  }
}
```

### This is to check if it is production or development..

```
 if (process.env.NODE_ENV === 'development') {
    //Do the dev error
    sendErrorDev(err, res);
  } else if (process.env.NODE_ENV === 'production') {

    let error = { ...err };
    if (error.name === 'CastError') error = handleCastErrorDB(error);

    // Do the prodcution error.
    sendErrorProd(error, res)
  }
}
```

**folder-utils**
**file: appError.js**
```
class AppError extends Error {
  constructor(message, statusCode) {
    super(message);

    this.statusCode = statusCode;
    this.status = `${statusCode}`.startsWith('4') ? 'fail' : 'error';
    this.isOperational = true;

    Error.captureStackTrace(this, this.constructor);
  }
}

module.exports = AppError;
```
If you find any error let me know, thank you.
![127 0 0 1_8000_api_v1_tours_SomeRandomPage - My Workspace 24-04-2023 03_17_52](https://user-images.githubusercontent.com/112542453/233868484-4031552e-684f-4e58-9b16-5718137265d6.png)

**Comment by jukha** [comment]
Hi, @SoumyaSubhrajit I was getting this same error whenever I tried to run the app using cmd or PowerShell Which is that changing NODE_ENV to production mode the request-response cycle never seems to be finishing. Tried out so many things but 'WSL linux terminal' only worked for me. How did you solve yours?

**Comment by SoumyaSubhrajit** [comment]
Not yet currently take hold on that project as soon I resolve the problem I will let you know.
