### ISSUE TITLE
Unable to clone the repoository

### ISSUE THREAD

**Issue by hassanpdn** [jonasschmedtmann/complete-node-bootcamp#225]
I am getting this error while cloning the repo: 
```
error: 7543 bytes of body are still expected | 242.00 KiB/s  
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

any idea whats wrong here?

**Comment by akozdev** [comment]
Maybe something from [this list](https://github.com/orgs/community/discussions/48568#discussioncomment-5108608) will help. If not, you can always download the repo as a ZIP archive.

**Comment by hassanpdn** [comment]
> Maybe something from [this list](https://github.com/orgs/community/discussions/48568#discussioncomment-5108608) will help. If not, you can always download the repo as a ZIP archive.

Tnx but didn't work for me.

**Comment by mekwossukoha** [comment]
I am having these same issues, I can't clone neither can I download the zip file

**Comment by hassanpdn** [comment]
Just cloned by adding a new ssh key and using ssh!
